export const gentiliciosData = [
  { provincia: 'Álava', gentilicio: 'alavés' },
  { provincia: 'Albacete', gentilicio: 'albaceteño' },
  { provincia: 'Alicante', gentilicio: 'alicantino' },
  { provincia: 'Almería', gentilicio: 'almeriense' },
  { provincia: 'Asturias', gentilicio: 'asturiano' },
  { provincia: 'Ávila', gentilicio: 'abulense' },
  { provincia: 'Badajoz', gentilicio: 'pacense' },
  { provincia: 'Barcelona', gentilicio: 'barcelonés' },
  { provincia: 'Burgos', gentilicio: 'burgalés' },
  { provincia: 'Cáceres', gentilicio: 'cacereño' },
  { provincia: 'Cádiz', gentilicio: 'gaditano' },
  { provincia: 'Cantabria', gentilicio: 'cántabro' },
  { provincia: 'Castellón', gentilicio: 'castellonense' },
  { provincia: 'Ciudad Real', gentilicio: 'ciudadrealeño' },
  { provincia: 'Córdoba', gentilicio: 'cordobés' },
  { provincia: 'Cuenca', gentilicio: 'conquense' },
  { provincia: 'Gerona', gentilicio: 'gerundense' },
  { provincia: 'Granada', gentilicio: 'granadino' },
  { provincia: 'Guadalajara', gentilicio: 'guadalajareño' },
  { provincia: 'Guipúzcoa', gentilicio: 'guipuzcoano' },
  { provincia: 'Huelva', gentilicio: 'onubense' },
  { provincia: 'Huesca', gentilicio: 'oscense' },
  { provincia: 'Islas Baleares', gentilicio: 'balear' },
  { provincia: 'Jaén', gentilicio: 'jienense' },
  { provincia: 'La Coruña', gentilicio: 'coruñés' },
  { provincia: 'La Rioja', gentilicio: 'riojano' },
  { provincia: 'Las Palmas', gentilicio: 'palmense' },
  { provincia: 'León', gentilicio: 'leonés' },
  { provincia: 'Lérida', gentilicio: 'leridano' },
  { provincia: 'Lugo', gentilicio: 'lucense' },
  { provincia: 'Madrid', gentilicio: 'madrileño' },
  { provincia: 'Málaga', gentilicio: 'malagueño' },
  { provincia: 'Murcia', gentilicio: 'murciano' },
  { provincia: 'Navarra', gentilicio: 'navarro' },
  { provincia: 'Orense', gentilicio: 'orense' },
  { provincia: 'Palencia', gentilicio: 'palentino' },
  { provincia: 'Pontevedra', gentilicio: 'pontevedrés' },
  { provincia: 'Salamanca', gentilicio: 'salmantino' },
  { provincia: 'Santa Cruz de Tenerife', gentilicio: 'tinerfeño' },
  { provincia: 'Segovia', gentilicio: 'segoviano' },
  { provincia: 'Sevilla', gentilicio: 'sevillano' },
  { provincia: 'Soria', gentilicio: 'soriano' },
  { provincia: 'Tarragona', gentilicio: 'tarraconense' },
  { provincia: 'Teruel', gentilicio: 'turolense' },
  { provincia: 'Toledo', gentilicio: 'toledano' },
  { provincia: 'Valencia', gentilicio: 'valenciano' },
  { provincia: 'Valladolid', gentilicio: 'vallisoletano' },
  { provincia: 'Vizcaya', gentilicio: 'vizcaíno' },
  { provincia: 'Zamora', gentilicio: 'zamorano' },
  { provincia: 'Zaragoza', gentilicio: 'zaragozano' },
];

export const acentuacionData = [
  { palabra: 'camión', tipo: 'aguda', regla: 'Las palabras agudas llevan tilde si terminan en vocal, -n o -s.' },
  { palabra: 'árbol', tipo: 'llana', regla: 'Las palabras llanas llevan tilde si NO terminan en vocal, -n o -s.' },
  { palabra: 'brújula', tipo: 'esdrújula', regla: 'Las palabras esdrújulas siempre llevan tilde.' },
  { palabra: 'pared', tipo: 'aguda', regla: 'Las palabras agudas que no terminan en vocal, -n o -s no llevan tilde.' },
  { palabra: 'césped', tipo: 'llana', regla: 'Las palabras llanas llevan tilde si NO terminan en vocal, -n o -s.' },
  { palabra: 'pájaro', tipo: 'esdrújula', regla: 'Las palabras esdrújulas siempre llevan tilde.' },
  { palabra: 'sofá', tipo: 'aguda', regla: 'Las palabras agudas llevan tilde si terminan en vocal, -n o -s.' },
  { palabra: 'mesa', tipo: 'llana', regla: 'Las palabras llanas que terminan en vocal, -n o -s no llevan tilde.' },
  { palabra: 'teléfono', tipo: 'esdrújula', regla: 'Las palabras esdrújulas siempre llevan tilde.' },
  { palabra: 'jugar', tipo: 'aguda', regla: 'Las palabras agudas que no terminan en vocal, -n o -s no llevan tilde.' },
  { palabra: 'lápiz', tipo: 'llana', regla: 'Las palabras llanas llevan tilde si NO terminan en vocal, -n o -s.' },
  { palabra: 'música', tipo: 'esdrújula', regla: 'Las palabras esdrújulas siempre llevan tilde.' },
];
