export const gentiliciosData = [
  { provincia: 'Álava', gentilicio: 'alavés' },
  { provincia: 'Albacete', gentilicio: 'albaceteño' },
  { provincia: 'Alicante', gentilicio: 'alicantino' },
  { provincia: 'Almería', gentilicio: 'almeriense' },
  { provincia: 'Asturias', gentilicio: 'asturiano' },
  { provincia: 'Ávila', gentilicio: 'abulense' },
  { provincia: 'Badajoz', gentilicio: 'pacense' },
  { provincia: 'Barcelona', gentilicio: 'barcelonés' },
  { provincia: 'Burgos', gentilicio: 'burgalés' },
  { provincia: 'Cáceres', gentilicio: 'cacereño' },
  { provincia: 'Cádiz', gentilicio: 'gaditano' },
  { provincia: 'Cantabria', gentilicio: 'cántabro' },
  { provincia: 'Castellón', gentilicio: 'castellonense' },
  { provincia: 'Ciudad Real', gentilicio: 'ciudadrealeño' },
  { provincia: 'Córdoba', gentilicio: 'cordobés' },
  { provincia: 'Cuenca', gentilicio: 'conquense' },
  { provincia: 'Gerona', gentilicio: 'gerundense' },
  { provincia: 'Granada', gentilicio: 'granadino' },
  { provincia: 'Guadalajara', gentilicio: 'guadalajareño' },
  { provincia: 'Guipúzcoa', gentilicio: 'guipuzcoano' },
  { provincia: 'Huelva', gentilicio: 'onubense' },
  { provincia: 'Huesca', gentilicio: 'oscense' },
  { provincia: 'Islas Baleares', gentilicio: 'balear' },
  { provincia: 'Jaén', gentilicio: 'jienense' },
  { provincia: 'La Coruña', gentilicio: 'coruñés' },
  { provincia: 'La Rioja', gentilicio: 'riojano' },
  { provincia: 'Las Palmas', gentilicio: 'palmense' },
  { provincia: 'León', gentilicio: 'leonés' },
  { provincia: 'Lérida', gentilicio: 'leridano' },
  { provincia: 'Lugo', gentilicio: 'lucense' },
  { provincia: 'Madrid', gentilicio: 'madrileño' },
  { provincia: 'Málaga', gentilicio: 'malagueño' },
  { provincia: 'Murcia', gentilicio: 'murciano' },
  { provincia: 'Navarra', gentilicio: 'navarro' },
  { provincia: 'Orense', gentilicio: 'orense' },
  { provincia: 'Palencia', gentilicio: 'palentino' },
  { provincia: 'Pontevedra', gentilicio: 'pontevedrés' },
  { provincia: 'Salamanca', gentilicio: 'salmantino' },
  { provincia: 'Santa Cruz de Tenerife', gentilicio: 'tinerfeño' },
  { provincia: 'Segovia', gentilicio: 'segoviano' },
  { provincia: 'Sevilla', gentilicio: 'sevillano' },
  { provincia: 'Soria', gentilicio: 'soriano' },
  { provincia: 'Tarragona', gentilicio: 'tarraconense' },
  { provincia: 'Teruel', gentilicio: 'turolense' },
  { provincia: 'Toledo', gentilicio: 'toledano' },
  { provincia: 'Valencia', gentilicio: 'valenciano' },
  { provincia: 'Valladolid', gentilicio: 'vallisoletano' },
  { provincia: 'Vizcaya', gentilicio: 'vizcaíno' },
  { provincia: 'Zamora', gentilicio: 'zamorano' },
  { provincia: 'Zaragoza', gentilicio: 'zaragozano' },
];

export const acentuacionData = [
  { palabra: 'camión', tipo: 'aguda', regla: 'Las palabras agudas llevan tilde si terminan en vocal, -n o -s.' },
  { palabra: 'árbol', tipo: 'llana', regla: 'Las palabras llanas llevan tilde si NO terminan en vocal, -n o -s.' },
  { palabra: 'brújula', tipo: 'esdrújula', regla: 'Las palabras esdrújulas siempre llevan tilde.' },
  { palabra: 'pared', tipo: 'aguda', regla: 'Las palabras agudas que no terminan en vocal, -n o -s no llevan tilde.' },
  { palabra: 'césped', tipo: 'llana', regla: 'Las palabras llanas llevan tilde si NO terminan en vocal, -n o -s.' },
  { palabra: 'pájaro', tipo: 'esdrújula', regla: 'Las palabras esdrújulas siempre llevan tilde.' },
  { palabra: 'sofá', tipo: 'aguda', regla: 'Las palabras agudas llevan tilde si terminan en vocal, -n o -s.' },
  { palabra: 'mesa', tipo: 'llana', regla: 'Las palabras llanas que terminan en vocal, -n o -s no llevan tilde.' },
  { palabra: 'teléfono', tipo: 'esdrújula', regla: 'Las palabras esdrújulas siempre llevan tilde.' },
  { palabra: 'jugar', tipo: 'aguda', regla: 'Las palabras agudas que no terminan en vocal, -n o -s no llevan tilde.' },
  { palabra: 'lápiz', tipo: 'llana', regla: 'Las palabras llanas llevan tilde si NO terminan en vocal, -n o -s.' },
  { palabra: 'música', tipo: 'esdrújula', regla: 'Las palabras esdrújulas siempre llevan tilde.' },
  { palabra: 'corazón', tipo: 'aguda', regla: 'Las palabras agudas llevan tilde si terminan en vocal, -n o -s.' },
  { palabra: 'débil', tipo: 'llana', regla: 'Las palabras llanas llevan tilde si NO terminan en vocal, -n o -s.' },
  { palabra: 'económico', tipo: 'esdrújula', regla: 'Las palabras esdrújulas siempre llevan tilde.' },
  { palabra: 'reloj', tipo: 'aguda', regla: 'Las palabras agudas que no terminan en vocal, -n o -s no llevan tilde.' },
  { palabra: 'azúcar', tipo: 'llana', regla: 'Las palabras llanas llevan tilde si NO terminan en vocal, -n o -s.' },
  { palabra: 'rápido', tipo: 'esdrújula', regla: 'Las palabras esdrújulas siempre llevan tilde.' },
  { palabra: 'café', tipo: 'aguda', regla: 'Las palabras agudas llevan tilde si terminan en vocal, -n o -s.' },
  { palabra: 'examen', tipo: 'llana', regla: 'Las palabras llanas que terminan en vocal, -n o -s no llevan tilde.' },
  { palabra: 'América', tipo: 'esdrújula', regla: 'Las palabras esdrújulas siempre llevan tilde.' },
  { palabra: 'amor', tipo: 'aguda', regla: 'Las palabras agudas que no terminan en vocal, -n o -s no llevan tilde.' },
  { palabra: 'túnel', tipo: 'llana', regla: 'Las palabras llanas llevan tilde si NO terminan en vocal, -n o -s.' },
  { palabra: 'plátano', tipo: 'esdrújula', regla: 'Las palabras esdrújulas siempre llevan tilde.' },
  { palabra: 'francés', tipo: 'aguda', regla: 'Las palabras agudas llevan tilde si terminan en vocal, -n o -s.' },
  { palabra: 'casa', tipo: 'llana', regla: 'Las palabras llanas que terminan en vocal, -n o -s no llevan tilde.' },
  { palabra: 'murciélago', tipo: 'esdrújula', regla: 'Las palabras esdrújulas siempre llevan tilde.' },
  { palabra: 'calor', tipo: 'aguda', regla: 'Las palabras agudas que no terminan en vocal, -n o -s no llevan tilde.' },
  { palabra: 'fácil', tipo: 'llana', regla: 'Las palabras llanas llevan tilde si NO terminan en vocal, -n o -s.' },
  { palabra: 'sábado', tipo: 'esdrújula', regla: 'Las palabras esdrújulas siempre llevan tilde.' },
  { palabra: 'inglés', tipo: 'aguda', regla: 'Las palabras agudas llevan tilde si terminan en vocal, -n o -s.' },
  { palabra: 'caracteres', tipo: 'llana', regla: 'Las palabras llanas que terminan en vocal, -n o -s no llevan tilde.' },
  { palabra: 'página', tipo: 'esdrújula', regla: 'Las palabras esdrújulas siempre llevan tilde.' },
  { palabra: 'amistad', tipo: 'aguda', regla: 'Las palabras agudas que no terminan en vocal, -n o -s no llevan tilde.' },
  { palabra: 'móvil', tipo: 'llana', regla: 'Las palabras llanas llevan tilde si NO terminan en vocal, -n o -s.' },
  { palabra: 'matemáticas', tipo: 'esdrújula', regla: 'Las palabras esdrújulas siempre llevan tilde.' },
  { palabra: 'además', tipo: 'aguda', regla: 'Las palabras agudas llevan tilde si terminan en vocal, -n o -s.' },
  { palabra: 'joven', tipo: 'llana', regla: 'Las palabras llanas que terminan en vocal, -n o -s no llevan tilde.' },
  { palabra: 'bolígrafo', tipo: 'esdrújula', regla: 'Las palabras esdrújulas siempre llevan tilde.' },
  { palabra: 'feliz', tipo: 'aguda', regla: 'Las palabras agudas que no terminan en vocal, -n o -s no llevan tilde.' },
  { palabra: 'dócil', tipo: 'llana', regla: 'Las palabras llanas llevan tilde si NO terminan en vocal, -n o -s.' },
  { palabra: 'océano', tipo: 'esdrújula', regla: 'Las palabras esdrújulas siempre llevan tilde.' },
  { palabra: 'bebé', tipo: 'aguda', regla: 'Las palabras agudas llevan tilde si terminan en vocal, -n o -s.' },
  { palabra: 'libro', tipo: 'llana', regla: 'Las palabras llanas que terminan en vocal, -n o -s no llevan tilde.' },
  { palabra: 'histórico', tipo: 'esdrújula', regla: 'Las palabras esdrújulas siempre llevan tilde.' },
  { palabra: 'hotel', tipo: 'aguda', regla: 'Las palabras agudas que no terminan en vocal, -n o -s no llevan tilde.' },
  { palabra: 'difícil', tipo: 'llana', regla: 'Las palabras llanas llevan tilde si NO terminan en vocal, -n o -s.' },
  { palabra: 'oxígeno', tipo: 'esdrújula', regla: 'Las palabras esdrújulas siempre llevan tilde.' },
  { palabra: 'sofá', tipo: 'aguda', regla: 'Las palabras agudas llevan tilde si terminan en vocal, -n o -s.' },
  { palabra: 'problema', tipo: 'llana', regla: 'Las palabras llanas que terminan en vocal, -n o -s no llevan tilde.' },
  { palabra: 'fantástico', tipo: 'esdrújula', regla: 'Las palabras esdrújulas siempre llevan tilde.' },
  { palabra: 'Madrid', tipo: 'aguda', regla: 'Las palabras agudas que no terminan en vocal, -n o -s no llevan tilde.' },
  { palabra: 'fértil', tipo: 'llana', regla: 'Las palabras llanas llevan tilde si NO terminan en vocal, -n o -s.' },
  { palabra: 'crónica', tipo: 'esdrújula', regla: 'Las palabras esdrújulas siempre llevan tilde.' },
  { palabra: 'almacén', tipo: 'aguda', regla: 'Las palabras agudas llevan tilde si terminan en vocal, -n o -s.' },
  { palabra: 'naranja', tipo: 'llana', regla: 'Las palabras llanas que terminan en vocal, -n o -s no llevan tilde.' },
  { palabra: 'geométrico', tipo: 'esdrújula', regla: 'Las palabras esdrújulas siempre llevan tilde.' },
  { palabra: 'animal', tipo: 'aguda', regla: 'Las palabras agudas que no terminan en vocal, -n o -s no llevan tilde.' },
  { palabra: 'hábil', tipo: 'llana', regla: 'Las palabras llanas llevan tilde si NO terminan en vocal, -n o -s.' },
  { palabra: 'héroe', tipo: 'esdrújula', regla: 'Las palabras esdrújulas siempre llevan tilde.' },
  { palabra: 'japonés', tipo: 'aguda', regla: 'Las palabras agudas llevan tilde si terminan en vocal, -n o -s.' },
  { palabra: 'manzana', tipo: 'llana', regla: 'Las palabras llanas que terminan en vocal, -n o -s no llevan tilde.' },
  { palabra: 'círculo', tipo: 'esdrújula', regla: 'Las palabras esdrújulas siempre llevan tilde.' },
  { palabra: 'ciudad', tipo: 'aguda', regla: 'Las palabras agudas que no terminan en vocal, -n o -s no llevan tilde.' },
  { palabra: 'frágil', tipo: 'llana', regla: 'Las palabras llanas llevan tilde si NO terminan en vocal, -n o -s.' },
  { palabra: 'lágrima', tipo: 'esdrújula', regla: 'Las palabras esdrújulas siempre llevan tilde.' },
  { palabra: 'pasión', tipo: 'aguda', regla: 'Las palabras agudas llevan tilde si terminan en vocal, -n o -s.' },
  { palabra: 'ventana', tipo: 'llana', regla: 'Las palabras llanas que terminan en vocal, -n o -s no llevan tilde.' },
  { palabra: 'gramática', tipo: 'esdrújula', regla: 'Las palabras esdrújulas siempre llevan tilde.' },
  { palabra: 'natural', tipo: 'aguda', regla: 'Las palabras agudas que no terminan en vocal, -n o -s no llevan tilde.' },
  { palabra: 'fósil', tipo: 'llana', regla: 'Las palabras llanas llevan tilde si NO terminan en vocal, -n o -s.' },
  { palabra: 'pirámide', tipo: 'esdrújula', regla: 'Las palabras esdrújulas siempre llevan tilde.' },
  { palabra: 'volcán', tipo: 'aguda', regla: 'Las palabras agudas llevan tilde si terminan en vocal, -n o -s.' },
  { palabra: 'lunes', tipo: 'llana', regla: 'Las palabras llanas que terminan en vocal, -n o -s no llevan tilde.' },
  { palabra: 'romántico', tipo: 'esdrújula', regla: 'Las palabras esdrújulas siempre llevan tilde.' },
  { palabra: 'azul', tipo: 'aguda', regla: 'Las palabras agudas que no terminan en vocal, -n o -s no llevan tilde.' },
  { palabra: 'inútil', tipo: 'llana', regla: 'Las palabras llanas llevan tilde si NO terminan en vocal, -n o -s.' },
  { palabra: 'semáforo', tipo: 'esdrújula', regla: 'Las palabras esdrújulas siempre llevan tilde.' },
  { palabra: 'jamás', tipo: 'aguda', regla: 'Las palabras agudas llevan tilde si terminan en vocal, -n o -s.' },
  { palabra: 'martes', tipo: 'llana', regla: 'Las palabras llanas que terminan en vocal, -n o -s no llevan tilde.' },
  { palabra: 'termómetro', tipo: 'esdrújula', regla: 'Las palabras esdrújulas siempre llevan tilde.' },
  { palabra: 'cantar', tipo: 'aguda', regla: 'Las palabras agudas que no terminan en vocal, -n o -s no llevan tilde.' },
  { palabra: 'mármol', tipo: 'llana', regla: 'Las palabras llanas llevan tilde si NO terminan en vocal, -n o -s.' },
  { palabra: 'vértebra', tipo: 'esdrújula', regla: 'Las palabras esdrújulas siempre llevan tilde.' },
  { palabra: 'limón', tipo: 'aguda', regla: 'Las palabras agudas llevan tilde si terminan en vocal, -n o -s.' },
  { palabra: 'volumen', tipo: 'llana', regla: 'Las palabras llanas que terminan en vocal, -n o -s no llevan tilde.' },
  { palabra: 'académico', tipo: 'esdrújula', regla: 'Las palabras esdrújulas siempre llevan tilde.' },
  { palabra: 'verdad', tipo: 'aguda', regla: 'Las palabras agudas que no terminan en vocal, -n o -s no llevan tilde.' },
  { palabra: 'récord', tipo: 'llana', regla: 'Las palabras llanas llevan tilde si NO terminan en vocal, -n o -s.' },
  { palabra: 'catástrofe', tipo: 'esdrújula', regla: 'Las palabras esdrújulas siempre llevan tilde.' },
  { palabra: 'menú', tipo: 'aguda', regla: 'Las palabras agudas llevan tilde si terminan en vocal, -n o -s.' },
  { palabra: 'imagen', tipo: 'llana', regla: 'Las palabras llanas que terminan en vocal, -n o -s no llevan tilde.' },
  { palabra: 'décimo', tipo: 'esdrújula', regla: 'Las palabras esdrújulas siempre llevan tilde.' },
  { palabra: 'borrador', tipo: 'aguda', regla: 'Las palabras agudas que no terminan en vocal, -n o -s no llevan tilde.' },
  { palabra: 'táctil', tipo: 'llana', regla: 'Las palabras llanas llevan tilde si NO terminan en vocal, -n o -s.' },
  { palabra: 'espectáculo', tipo: 'esdrújula', regla: 'Las palabras esdrújulas siempre llevan tilde.' },
  { palabra: 'papel', tipo: 'aguda', regla: 'Las palabras agudas que no terminan en vocal, -n o -s no llevan tilde.' },
  { palabra: 'carácter', tipo: 'llana', regla: 'Las palabras llanas llevan tilde si NO terminan en vocal, -n o -s.' },
  { palabra: 'ídolo', tipo: 'esdrújula', regla: 'Las palabras esdrújulas siempre llevan tilde.' },
  { palabra: 'sillón', tipo: 'aguda', regla: 'Las palabras agudas llevan tilde si terminan en vocal, -n o -s.' },
  { palabra: 'orden', tipo: 'llana', regla: 'Las palabras llanas que terminan en vocal, -n o -s no llevan tilde.' },
  { palabra: 'cáscara', tipo: 'esdrújula', regla: 'Las palabras esdrújulas siempre llevan tilde.' },
  { palabra: 'motor', tipo: 'aguda', regla: 'Las palabras agudas que no terminan en vocal, -n o -s no llevan tilde.' },
  { palabra: 'póster', tipo: 'llana', regla: 'Las palabras llanas llevan tilde si NO terminan en vocal, -n o -s.' },
  { palabra: 'película', tipo: 'esdrújula', regla: 'Las palabras esdrújulas siempre llevan tilde.' },
  { palabra: 'rubí', tipo: 'aguda', regla: 'Las palabras agudas llevan tilde si terminan en vocal, -n o -s.' },
  { palabra: 'virgen', tipo: 'llana', regla: 'Las palabras llanas que terminan en vocal, -n o -s no llevan tilde.' },
  { palabra: 'centímetro', tipo: 'esdrújula', regla: 'Las palabras esdrújulas siempre llevan tilde.' },
  { palabra: 'tambor', tipo: 'aguda', regla: 'Las palabras agudas que no terminan en vocal, -n o -s no llevan tilde.' },
  { palabra: 'trébol', tipo: 'llana', regla: 'Las palabras llanas llevan tilde si NO terminan en vocal, -n o -s.' },
  { palabra: 'periódico', tipo: 'esdrújula', regla: 'Las palabras esdrújulas siempre llevan tilde.' },
  { palabra: 'París', tipo: 'aguda', regla: 'Las palabras agudas llevan tilde si terminan en vocal, -n o -s.' },
  { palabra: 'amigo', tipo: 'llana', regla: 'Las palabras llanas que terminan en vocal, -n o -s no llevan tilde.' },
  { palabra: 'paréntesis', tipo: 'esdrújula', regla: 'Las palabras esdrújulas siempre llevan tilde.' },
  { palabra: 'capaz', tipo: 'aguda', regla: 'Las palabras agudas que no terminan en vocal, -n o -s no llevan tilde.' },
  { palabra: 'ágil', tipo: 'llana', regla: 'Las palabras llanas llevan tilde si NO terminan en vocal, -n o -s.' },
  { palabra: 'tarántula', tipo: 'esdrújula', regla: 'Las palabras esdrújulas siempre llevan tilde.' },
  { palabra: 'ración', tipo: 'aguda', regla: 'Las palabras agudas llevan tilde si terminan en vocal, -n o -s.' },
  { palabra: 'adulto', tipo: 'llana', regla: 'Las palabras llanas que terminan en vocal, -n o -s no llevan tilde.' },
  { palabra: 'cántaro', tipo: 'esdrújula', regla: 'Las palabras esdrújulas siempre llevan tilde.' },
  { palabra: 'nariz', tipo: 'aguda', regla: 'Las palabras agudas que no terminan en vocal, -n o -s no llevan tilde.' },
  { palabra: 'álbum', tipo: 'llana', regla: 'Las palabras llanas llevan tilde si NO terminan en vocal, -n o -s.' },
  { palabra: 'libélula', tipo: 'esdrújula', regla: 'Las palabras esdrújulas siempre llevan tilde.' },
  { palabra: 'interés', tipo: 'aguda', regla: 'Las palabras agudas llevan tilde si terminan en vocal, -n o -s.' },
  { palabra: 'zapato', tipo: 'llana', regla: 'Las palabras llanas que terminan en vocal, -n o -s no llevan tilde.' },
  { palabra: 'vértigo', tipo: 'esdrújula', regla: 'Las palabras esdrújulas siempre llevan tilde.' },
  { palabra: 'dolor', tipo: 'aguda', regla: 'Las palabras agudas que no terminan en vocal, -n o -s no llevan tilde.' },
  { palabra: 'célebre', tipo: 'esdrújula', regla: 'Las palabras esdrújulas siempre llevan tilde.' },
  { palabra: 'canción', tipo: 'aguda', regla: 'Las palabras agudas llevan tilde si terminan en vocal, -n o -s.' },
  { palabra: 'mástil', tipo: 'llana', regla: 'Las palabras llanas llevan tilde si NO terminan en vocal, -n o -s.' },
  { palabra: 'lámina', tipo: 'esdrújula', regla: 'Las palabras esdrújulas siempre llevan tilde.' },
  { palabra: 'ordenador', tipo: 'aguda', regla: 'Las palabras agudas que no terminan en vocal, -n o -s no llevan tilde.' },
  { palabra: 'clímax', tipo: 'llana', regla: 'Las palabras llanas llevan tilde si NO terminan en vocal, -n o -s.' },
  { palabra: 'rídiculo', tipo: 'esdrújula', regla: 'Las palabras esdrújulas siempre llevan tilde.' },
  { palabra: 'avión', tipo: 'aguda', regla: 'Las palabras agudas llevan tilde si terminan en vocal, -n o -s.' },
  { palabra: 'resumen', tipo: 'llana', regla: 'Las palabras llanas que terminan en vocal, -n o -s no llevan tilde.' },
  { palabra: 'dámelo', tipo: 'esdrújula', regla: 'Las palabras esdrújulas siempre llevan tilde.' },
  { palabra: 'ratón', tipo: 'aguda', regla: 'Las palabras agudas llevan tilde si terminan en vocal, -n o -s.' },
  { palabra: 'tórax', tipo: 'llana', regla: 'Las palabras llanas llevan tilde si NO terminan en vocal, -n o -s.' },
  { palabra: 'cómpralo', tipo: 'esdrújula', regla: 'Las palabras esdrújulas siempre llevan tilde.' }
];

export const acentuacionVocalData = [
  { palabraCompleta: 'camión', palabraIncompleta: 'cami_n', vocalCorrecta: 'ó', vocalIncorrecta: 'o', regla: 'Las palabras agudas llevan tilde si terminan en vocal, -n o -s.' },
  { palabraCompleta: 'árbol', palabraIncompleta: '_rbol', vocalCorrecta: 'á', vocalIncorrecta: 'a', regla: 'Las palabras llanas llevan tilde si NO terminan en vocal, -n o -s.' },
  { palabraCompleta: 'brújula', palabraIncompleta: 'br_jula', vocalCorrecta: 'ú', vocalIncorrecta: 'u', regla: 'Las palabras esdrújulas siempre llevan tilde.' },
  { palabraCompleta: 'pared', palabraIncompleta: 'par_d', vocalCorrecta: 'e', vocalIncorrecta: 'é', regla: 'Las palabras agudas que no terminan en vocal, -n o -s no llevan tilde.' },
  { palabraCompleta: 'césped', palabraIncompleta: 'c_sped', vocalCorrecta: 'é', vocalIncorrecta: 'e', regla: 'Las palabras llanas llevan tilde si NO terminan en vocal, -n o -s.' },
  { palabraCompleta: 'pájaro', palabraIncompleta: 'p_jaro', vocalCorrecta: 'á', vocalIncorrecta: 'a', regla: 'Las palabras esdrújulas siempre llevan tilde.' },
  { palabraCompleta: 'sofá', palabraIncompleta: 'sof_', vocalCorrecta: 'á', vocalIncorrecta: 'a', regla: 'Las palabras agudas llevan tilde si terminan en vocal, -n o -s.' },
  { palabraCompleta: 'mesa', palabraIncompleta: 'm_sa', vocalCorrecta: 'e', vocalIncorrecta: 'é', regla: 'Las palabras llanas que terminan en vocal, -n o -s no llevan tilde.' },
  { palabraCompleta: 'teléfono', palabraIncompleta: 'tel_fono', vocalCorrecta: 'é', vocalIncorrecta: 'e', regla: 'Las palabras esdrújulas siempre llevan tilde.' },
  { palabraCompleta: 'jugar', palabraIncompleta: 'jug_r', vocalCorrecta: 'a', vocalIncorrecta: 'á', regla: 'Las palabras agudas que no terminan en vocal, -n o -s no llevan tilde.' },
  { palabraCompleta: 'lápiz', palabraIncompleta: 'l_piz', vocalCorrecta: 'á', vocalIncorrecta: 'a', regla: 'Las palabras llanas llevan tilde si NO terminan en vocal, -n o -s.' },
  { palabraCompleta: 'música', palabraIncompleta: 'm_sica', vocalCorrecta: 'ú', vocalIncorrecta: 'u', regla: 'Las palabras esdrújulas siempre llevan tilde.' },
  { palabraCompleta: 'corazón', palabraIncompleta: 'coraz_n', vocalCorrecta: 'ó', vocalIncorrecta: 'o', regla: 'Las palabras agudas llevan tilde si terminan en vocal, -n o -s.' },
  { palabraCompleta: 'débil', palabraIncompleta: 'd_bil', vocalCorrecta: 'é', vocalIncorrecta: 'e', regla: 'Las palabras llanas llevan tilde si NO terminan en vocal, -n o -s.' },
  { palabraCompleta: 'económico', palabraIncompleta: 'econ_mico', vocalCorrecta: 'ó', vocalIncorrecta: 'o', regla: 'Las palabras esdrújulas siempre llevan tilde.' },
  { palabraCompleta: 'reloj', palabraIncompleta: 'rel_j', vocalCorrecta: 'o', vocalIncorrecta: 'ó', regla: 'Las palabras agudas que no terminan en vocal, -n o -s no llevan tilde.' },
  { palabraCompleta: 'azúcar', palabraIncompleta: 'az_car', vocalCorrecta: 'ú', vocalIncorrecta: 'u', regla: 'Las palabras llanas llevan tilde si NO terminan en vocal, -n o -s.' },
  { palabraCompleta: 'rápido', palabraIncompleta: 'r_pido', vocalCorrecta: 'á', vocalIncorrecta: 'a', regla: 'Las palabras esdrújulas siempre llevan tilde.' },
  { palabraCompleta: 'café', palabraIncompleta: 'caf_', vocalCorrecta: 'é', vocalIncorrecta: 'e', regla: 'Las palabras agudas llevan tilde si terminan en vocal, -n o -s.' },
  { palabraCompleta: 'examen', palabraIncompleta: 'ex_men', vocalCorrecta: 'a', vocalIncorrecta: 'á', regla: 'Las palabras llanas que terminan en vocal, -n o -s no llevan tilde.' },
  { palabraCompleta: 'América', palabraIncompleta: 'Am_rica', vocalCorrecta: 'é', vocalIncorrecta: 'e', regla: 'Las palabras esdrújulas siempre llevan tilde.' },
  { palabraCompleta: 'amor', palabraIncompleta: 'am_r', vocalCorrecta: 'o', vocalIncorrecta: 'ó', regla: 'Las palabras agudas que no terminan en vocal, -n o -s no llevan tilde.' },
  { palabraCompleta: 'túnel', palabraIncompleta: 't_nel', vocalCorrecta: 'ú', vocalIncorrecta: 'u', regla: 'Las palabras llanas llevan tilde si NO terminan en vocal, -n o -s.' },
  { palabraCompleta: 'plátano', palabraIncompleta: 'pl_tano', vocalCorrecta: 'á', vocalIncorrecta: 'a', regla: 'Las palabras esdrújulas siempre llevan tilde.' },
  { palabraCompleta: 'francés', palabraIncompleta: 'franc_s', vocalCorrecta: 'é', vocalIncorrecta: 'e', regla: 'Las palabras agudas llevan tilde si terminan en vocal, -n o -s.' },
  { palabraCompleta: 'casa', palabraIncompleta: 'c_sa', vocalCorrecta: 'a', vocalIncorrecta: 'á', regla: 'Las palabras llanas que terminan en vocal, -n o -s no llevan tilde.' },
  { palabraCompleta: 'murciélago', palabraIncompleta: 'murci_lago', vocalCorrecta: 'é', vocalIncorrecta: 'e', regla: 'Las palabras esdrújulas siempre llevan tilde.' },
  { palabraCompleta: 'calor', palabraIncompleta: 'cal_r', vocalCorrecta: 'o', vocalIncorrecta: 'ó', regla: 'Las palabras agudas que no terminan en vocal, -n o -s no llevan tilde.' },
  { palabraCompleta: 'fácil', palabraIncompleta: 'f_cil', vocalCorrecta: 'á', vocalIncorrecta: 'a', regla: 'Las palabras llanas llevan tilde si NO terminan en vocal, -n o -s.' },
  { palabraCompleta: 'sábado', palabraIncompleta: 's_bado', vocalCorrecta: 'á', vocalIncorrecta: 'a', regla: 'Las palabras esdrújulas siempre llevan tilde.' },
  { palabraCompleta: 'inglés', palabraIncompleta: 'ingl_s', vocalCorrecta: 'é', vocalIncorrecta: 'e', regla: 'Las palabras agudas llevan tilde si terminan en vocal, -n o -s.' },
  { palabraCompleta: 'caracteres', palabraIncompleta: 'caract_res', vocalCorrecta: 'e', vocalIncorrecta: 'é', regla: 'Las palabras llanas que terminan en vocal, -n o -s no llevan tilde.' },
  { palabraCompleta: 'página', palabraIncompleta: 'p_gina', vocalCorrecta: 'á', vocalIncorrecta: 'a', regla: 'Las palabras esdrújulas siempre llevan tilde.' },
  { palabraCompleta: 'amistad', palabraIncompleta: 'amist_d', vocalCorrecta: 'a', vocalIncorrecta: 'á', regla: 'Las palabras agudas que no terminan en vocal, -n o -s no llevan tilde.' },
  { palabraCompleta: 'móvil', palabraIncompleta: 'm_vil', vocalCorrecta: 'ó', vocalIncorrecta: 'o', regla: 'Las palabras llanas llevan tilde si NO terminan en vocal, -n o -s.' },
  { palabraCompleta: 'matemáticas', palabraIncompleta: 'matem_ticas', vocalCorrecta: 'á', vocalIncorrecta: 'a', regla: 'Las palabras esdrújulas siempre llevan tilde.' },
  { palabraCompleta: 'además', palabraIncompleta: 'adem_s', vocalCorrecta: 'á', vocalIncorrecta: 'a', regla: 'Las palabras agudas llevan tilde si terminan en vocal, -n o -s.' },
  { palabraCompleta: 'joven', palabraIncompleta: 'j_ven', vocalCorrecta: 'o', vocalIncorrecta: 'ó', regla: 'Las palabras llanas que terminan en vocal, -n o -s no llevan tilde.' },
  { palabraCompleta: 'bolígrafo', palabraIncompleta: 'bol_grafo', vocalCorrecta: 'í', vocalIncorrecta: 'i', regla: 'Las palabras esdrújulas siempre llevan tilde.' },
  { palabraCompleta: 'feliz', palabraIncompleta: 'fel_z', vocalCorrecta: 'i', vocalIncorrecta: 'í', regla: 'Las palabras agudas que no terminan en vocal, -n o -s no llevan tilde.' },
  { palabraCompleta: 'dócil', palabraIncompleta: 'd_cil', vocalCorrecta: 'ó', vocalIncorrecta: 'o', regla: 'Las palabras llanas llevan tilde si NO terminan en vocal, -n o -s.' },
  { palabraCompleta: 'océano', palabraIncompleta: 'oc_ano', vocalCorrecta: 'é', vocalIncorrecta: 'e', regla: 'Las palabras esdrújulas siempre llevan tilde.' },
  { palabraCompleta: 'bebé', palabraIncompleta: 'beb_', vocalCorrecta: 'é', vocalIncorrecta: 'e', regla: 'Las palabras agudas llevan tilde si terminan en vocal, -n o -s.' },
  { palabraCompleta: 'libro', palabraIncompleta: 'l_bro', vocalCorrecta: 'i', vocalIncorrecta: 'í', regla: 'Las palabras llanas que terminan en vocal, -n o -s no llevan tilde.' },
  { palabraCompleta: 'histórico', palabraIncompleta: 'hist_rico', vocalCorrecta: 'ó', vocalIncorrecta: 'o', regla: 'Las palabras esdrújulas siempre llevan tilde.' },
  { palabraCompleta: 'hotel', palabraIncompleta: 'hot_l', vocalCorrecta: 'e', vocalIncorrecta: 'é', regla: 'Las palabras agudas que no terminan en vocal, -n o -s no llevan tilde.' },
  { palabraCompleta: 'difícil', palabraIncompleta: 'dif_cil', vocalCorrecta: 'í', vocalIncorrecta: 'i', regla: 'Las palabras llanas llevan tilde si NO terminan en vocal, -n o -s.' },
  { palabraCompleta: 'oxígeno', palabraIncompleta: 'ox_geno', vocalCorrecta: 'í', vocalIncorrecta: 'i', regla: 'Las palabras esdrújulas siempre llevan tilde.' },
  { palabraCompleta: 'sofá', palabraIncompleta: 'sof_', vocalCorrecta: 'á', vocalIncorrecta: 'a', regla: 'Las palabras agudas llevan tilde si terminan en vocal, -n o -s.' },
  { palabraCompleta: 'problema', palabraIncompleta: 'probl_ma', vocalCorrecta: 'e', vocalIncorrecta: 'é', regla: 'Las palabras llanas que terminan en vocal, -n o -s no llevan tilde.' },
  { palabraCompleta: 'fantástico', palabraIncompleta: 'fant_stico', vocalCorrecta: 'á', vocalIncorrecta: 'a', regla: 'Las palabras esdrújulas siempre llevan tilde.' },
  { palabraCompleta: 'Madrid', palabraIncompleta: 'Madr_d', vocalCorrecta: 'i', vocalIncorrecta: 'í', regla: 'Las palabras agudas que no terminan en vocal, -n o -s no llevan tilde.' },
  { palabraCompleta: 'fértil', palabraIncompleta: 'f_rtil', vocalCorrecta: 'é', vocalIncorrecta: 'e', regla: 'Las palabras llanas llevan tilde si NO terminan en vocal, -n o -s.' },
  { palabraCompleta: 'crónica', palabraIncompleta: 'cr_nica', vocalCorrecta: 'ó', vocalIncorrecta: 'o', regla: 'Las palabras esdrújulas siempre llevan tilde.' },
  { palabraCompleta: 'almacén', palabraIncompleta: 'almac_n', vocalCorrecta: 'é', vocalIncorrecta: 'e', regla: 'Las palabras agudas llevan tilde si terminan en vocal, -n o -s.' },
  { palabraCompleta: 'naranja', palabraIncompleta: 'nar_nja', vocalCorrecta: 'a', vocalIncorrecta: 'á', regla: 'Las palabras llanas que terminan en vocal, -n o -s no llevan tilde.' },
  { palabraCompleta: 'geométrico', palabraIncompleta: 'geom_trico', vocalCorrecta: 'é', vocalIncorrecta: 'e', regla: 'Las palabras esdrújulas siempre llevan tilde.' },
  { palabraCompleta: 'animal', palabraIncompleta: 'anim_l', vocalCorrecta: 'a', vocalIncorrecta: 'á', regla: 'Las palabras agudas que no terminan en vocal, -n o -s no llevan tilde.' },
  { palabraCompleta: 'hábil', palabraIncompleta: 'h_bil', vocalCorrecta: 'á', vocalIncorrecta: 'a', regla: 'Las palabras llanas llevan tilde si NO terminan en vocal, -n o -s.' },
  { palabraCompleta: 'héroe', palabraIncompleta: 'h_roe', vocalCorrecta: 'é', vocalIncorrecta: 'e', regla: 'Las palabras esdrújulas siempre llevan tilde.' },
  { palabraCompleta: 'japonés', palabraIncompleta: 'japon_s', vocalCorrecta: 'é', vocalIncorrecta: 'e', regla: 'Las palabras agudas llevan tilde si terminan en vocal, -n o -s.' },
  { palabraCompleta: 'manzana', palabraIncompleta: 'manz_na', vocalCorrecta: 'a', vocalIncorrecta: 'á', regla: 'Las palabras llanas que terminan en vocal, -n o -s no llevan tilde.' },
  { palabraCompleta: 'círculo', palabraIncompleta: 'c_rculo', vocalCorrecta: 'í', vocalIncorrecta: 'i', regla: 'Las palabras esdrújulas siempre llevan tilde.' },
  { palabraCompleta: 'ciudad', palabraIncompleta: 'ciud_d', vocalCorrecta: 'a', vocalIncorrecta: 'á', regla: 'Las palabras agudas que no terminan en vocal, -n o -s no llevan tilde.' },
  { palabraCompleta: 'frágil', palabraIncompleta: 'fr_gil', vocalCorrecta: 'á', vocalIncorrecta: 'a', regla: 'Las palabras llanas llevan tilde si NO terminan en vocal, -n o -s.' },
  { palabraCompleta: 'lágrima', palabraIncompleta: 'l_grima', vocalCorrecta: 'á', vocalIncorrecta: 'a', regla: 'Las palabras esdrújulas siempre llevan tilde.' },
  { palabraCompleta: 'pasión', palabraIncompleta: 'pasi_n', vocalCorrecta: 'ó', vocalIncorrecta: 'o', regla: 'Las palabras agudas llevan tilde si terminan en vocal, -n o -s.' },
  { palabraCompleta: 'ventana', palabraIncompleta: 'vent_na', vocalCorrecta: 'a', vocalIncorrecta: 'á', regla: 'Las palabras llanas que terminan en vocal, -n o -s no llevan tilde.' },
  { palabraCompleta: 'gramática', palabraIncompleta: 'gram_tica', vocalCorrecta: 'á', vocalIncorrecta: 'a', regla: 'Las palabras esdrújulas siempre llevan tilde.' },
  { palabraCompleta: 'natural', palabraIncompleta: 'natur_l', vocalCorrecta: 'a', vocalIncorrecta: 'á', regla: 'Las palabras agudas que no terminan en vocal, -n o -s no llevan tilde.' },
  { palabraCompleta: 'fósil', palabraIncompleta: 'f_sil', vocalCorrecta: 'ó', vocalIncorrecta: 'o', regla: 'Las palabras llanas llevan tilde si NO terminan en vocal, -n o -s.' },
  { palabraCompleta: 'pirámide', palabraIncompleta: 'pir_mide', vocalCorrecta: 'á', vocalIncorrecta: 'a', regla: 'Las palabras esdrújulas siempre llevan tilde.' },
  { palabraCompleta: 'volcán', palabraIncompleta: 'volc_n', vocalCorrecta: 'á', vocalIncorrecta: 'a', regla: 'Las palabras agudas llevan tilde si terminan en vocal, -n o -s.' },
  { palabraCompleta: 'lunes', palabraIncompleta: 'l_nes', vocalCorrecta: 'u', vocalIncorrecta: 'ú', regla: 'Las palabras llanas que terminan en vocal, -n o -s no llevan tilde.' },
  { palabraCompleta: 'romántico', palabraIncompleta: 'rom_ntico', vocalCorrecta: 'á', vocalIncorrecta: 'a', regla: 'Las palabras esdrújulas siempre llevan tilde.' },
  { palabraCompleta: 'azul', palabraIncompleta: 'az_l', vocalCorrecta: 'u', vocalIncorrecta: 'ú', regla: 'Las palabras agudas que no terminan en vocal, -n o -s no llevan tilde.' },
  { palabraCompleta: 'inútil', palabraIncompleta: 'in_til', vocalCorrecta: 'ú', vocalIncorrecta: 'u', regla: 'Las palabras llanas llevan tilde si NO terminan en vocal, -n o -s.' },
  { palabraCompleta: 'semáforo', palabraIncompleta: 'sem_foro', vocalCorrecta: 'á', vocalIncorrecta: 'a', regla: 'Las palabras esdrújulas siempre llevan tilde.' },
  { palabraCompleta: 'jamás', palabraIncompleta: 'jam_s', vocalCorrecta: 'á', vocalIncorrecta: 'a', regla: 'Las palabras agudas llevan tilde si terminan en vocal, -n o -s.' },
  { palabraCompleta: 'martes', palabraIncompleta: 'm_rtes', vocalCorrecta: 'a', vocalIncorrecta: 'á', regla: 'Las palabras llanas que terminan en vocal, -n o -s no llevan tilde.' },
  { palabraCompleta: 'termómetro', palabraIncompleta: 'term_metro', vocalCorrecta: 'ó', vocalIncorrecta: 'o', regla: 'Las palabras esdrújulas siempre llevan tilde.' },
  { palabraCompleta: 'cantar', palabraIncompleta: 'cant_r', vocalCorrecta: 'a', vocalIncorrecta: 'á', regla: 'Las palabras agudas que no terminan en vocal, -n o -s no llevan tilde.' },
  { palabraCompleta: 'mármol', palabraIncompleta: 'm_rmol', vocalCorrecta: 'á', vocalIncorrecta: 'a', regla: 'Las palabras llanas llevan tilde si NO terminan en vocal, -n o -s.' },
  { palabraCompleta: 'vértebra', palabraIncompleta: 'v_rtebra', vocalCorrecta: 'é', vocalIncorrecta: 'e', regla: 'Las palabras esdrújulas siempre llevan tilde.' },
  { palabraCompleta: 'limón', palabraIncompleta: 'lim_n', vocalCorrecta: 'ó', vocalIncorrecta: 'o', regla: 'Las palabras agudas llevan tilde si terminan en vocal, -n o -s.' },
  { palabraCompleta: 'volumen', palabraIncompleta: 'vol_men', vocalCorrecta: 'u', vocalIncorrecta: 'ú', regla: 'Las palabras llanas que terminan en vocal, -n o -s no llevan tilde.' },
  { palabraCompleta: 'académico', palabraIncompleta: 'acad_mico', vocalCorrecta: 'é', vocalIncorrecta: 'e', regla: 'Las palabras esdrújulas siempre llevan tilde.' },
  { palabraCompleta: 'verdad', palabraIncompleta: 'verd_d', vocalCorrecta: 'a', vocalIncorrecta: 'á', regla: 'Las palabras agudas que no terminan en vocal, -n o -s no llevan tilde.' },
  { palabraCompleta: 'récord', palabraIncompleta: 'r_cord', vocalCorrecta: 'é', vocalIncorrecta: 'e', regla: 'Las palabras llanas llevan tilde si NO terminan en vocal, -n o -s.' },
  { palabraCompleta: 'catástrofe', palabraIncompleta: 'cat_strofe', vocalCorrecta: 'á', vocalIncorrecta: 'a', regla: 'Las palabras esdrújulas siempre llevan tilde.' },
  { palabraCompleta: 'menú', palabraIncompleta: 'men_', vocalCorrecta: 'ú', vocalIncorrecta: 'u', regla: 'Las palabras agudas llevan tilde si terminan en vocal, -n o -s.' },
  { palabraCompleta: 'imagen', palabraIncompleta: 'im_gen', vocalCorrecta: 'a', vocalIncorrecta: 'á', regla: 'Las palabras llanas que terminan en vocal, -n o -s no llevan tilde.' },
  { palabraCompleta: 'décimo', palabraIncompleta: 'd_cimo', vocalCorrecta: 'é', vocalIncorrecta: 'e', regla: 'Las palabras esdrújulas siempre llevan tilde.' },
  { palabraCompleta: 'borrador', palabraIncompleta: 'borrad_r', vocalCorrecta: 'o', vocalIncorrecta: 'ó', regla: 'Las palabras agudas que no terminan en vocal, -n o -s no llevan tilde.' },
  { palabraCompleta: 'táctil', palabraIncompleta: 't_ctil', vocalCorrecta: 'á', vocalIncorrecta: 'a', regla: 'Las palabras llanas llevan tilde si NO terminan en vocal, -n o -s.' },
  { palabraCompleta: 'espectáculo', palabraIncompleta: 'espect_culo', vocalCorrecta: 'á', vocalIncorrecta: 'a', regla: 'Las palabras esdrújulas siempre llevan tilde.' },
  { palabraCompleta: 'papel', palabraIncompleta: 'pap_l', vocalCorrecta: 'e', vocalIncorrecta: 'é', regla: 'Las palabras agudas que no terminan en vocal, -n o -s no llevan tilde.' },
  { palabraCompleta: 'carácter', palabraIncompleta: 'car_cter', vocalCorrecta: 'á', vocalIncorrecta: 'a', regla: 'Las palabras llanas llevan tilde si NO terminan en vocal, -n o -s.' },
  { palabraCompleta: 'ídolo', palabraIncompleta: '_dolo', vocalCorrecta: 'í', vocalIncorrecta: 'i', regla: 'Las palabras esdrújulas siempre llevan tilde.' },
  { palabraCompleta: 'sillón', palabraIncompleta: 'sill_n', vocalCorrecta: 'ó', vocalIncorrecta: 'o', regla: 'Las palabras agudas llevan tilde si terminan en vocal, -n o -s.' },
  { palabraCompleta: 'orden', palabraIncompleta: '_rden', vocalCorrecta: 'o', vocalIncorrecta: 'ó', regla: 'Las palabras llanas que terminan en vocal, -n o -s no llevan tilde.' },
  { palabraCompleta: 'cáscara', palabraIncompleta: 'c_scara', vocalCorrecta: 'á', vocalIncorrecta: 'a', regla: 'Las palabras esdrújulas siempre llevan tilde.' },
  { palabraCompleta: 'motor', palabraIncompleta: 'mot_r', vocalCorrecta: 'o', vocalIncorrecta: 'ó', regla: 'Las palabras agudas que no terminan en vocal, -n o -s no llevan tilde.' },
  { palabraCompleta: 'póster', palabraIncompleta: 'p_ster', vocalCorrecta: 'ó', vocalIncorrecta: 'o', regla: 'Las palabras llanas llevan tilde si NO terminan en vocal, -n o -s.' },
  { palabraCompleta: 'película', palabraIncompleta: 'pel_cula', vocalCorrecta: 'í', vocalIncorrecta: 'i', regla: 'Las palabras esdrújulas siempre llevan tilde.' },
  { palabraCompleta: 'rubí', palabraIncompleta: 'rub_', vocalCorrecta: 'í', vocalIncorrecta: 'i', regla: 'Las palabras agudas llevan tilde si terminan en vocal, -n o -s.' },
  { palabraCompleta: 'virgen', palabraIncompleta: 'v_rgen', vocalCorrecta: 'i', vocalIncorrecta: 'í', regla: 'Las palabras llanas que terminan en vocal, -n o -s no llevan tilde.' },
  { palabraCompleta: 'centímetro', palabraIncompleta: 'cent_metro', vocalCorrecta: 'í', vocalIncorrecta: 'i', regla: 'Las palabras esdrújulas siempre llevan tilde.' },
  { palabraCompleta: 'tambor', palabraIncompleta: 'tamb_r', vocalCorrecta: 'o', vocalIncorrecta: 'ó', regla: 'Las palabras agudas que no terminan en vocal, -n o -s no llevan tilde.' },
  { palabraCompleta: 'trébol', palabraIncompleta: 'tr_bol', vocalCorrecta: 'é', vocalIncorrecta: 'e', regla: 'Las palabras llanas llevan tilde si NO terminan en vocal, -n o -s.' },
  { palabraCompleta: 'periódico', palabraIncompleta: 'peri_dico', vocalCorrecta: 'ó', vocalIncorrecta: 'o', regla: 'Las palabras esdrújulas siempre llevan tilde.' },
  { palabraCompleta: 'París', palabraIncompleta: 'Par_s', vocalCorrecta: 'í', vocalIncorrecta: 'i', regla: 'Las palabras agudas llevan tilde si terminan en vocal, -n o -s.' },
  { palabraCompleta: 'amigo', palabraIncompleta: 'am_go', vocalCorrecta: 'i', vocalIncorrecta: 'í', regla: 'Las palabras llanas que terminan en vocal, -n o -s no llevan tilde.' },
  { palabraCompleta: 'paréntesis', palabraIncompleta: 'par_ntesis', vocalCorrecta: 'é', vocalIncorrecta: 'e', regla: 'Las palabras esdrújulas siempre llevan tilde.' },
  { palabraCompleta: 'capaz', palabraIncompleta: 'cap_z', vocalCorrecta: 'a', vocalIncorrecta: 'á', regla: 'Las palabras agudas que no terminan en vocal, -n o -s no llevan tilde.' },
  { palabraCompleta: 'ágil', palabraIncompleta: '_gil', vocalCorrecta: 'á', vocalIncorrecta: 'a', regla: 'Las palabras llanas llevan tilde si NO terminan en vocal, -n o -s.' },
  { palabraCompleta: 'tarántula', palabraIncompleta: 'tar_ntula', vocalCorrecta: 'á', vocalIncorrecta: 'a', regla: 'Las palabras esdrújulas siempre llevan tilde.' },
  { palabraCompleta: 'ración', palabraIncompleta: 'raci_n', vocalCorrecta: 'ó', vocalIncorrecta: 'o', regla: 'Las palabras agudas llevan tilde si terminan en vocal, -n o -s.' },
  { palabraCompleta: 'adulto', palabraIncompleta: 'ad_lto', vocalCorrecta: 'u', vocalIncorrecta: 'ú', regla: 'Las palabras llanas que terminan en vocal, -n o -s no llevan tilde.' },
  { palabraCompleta: 'cántaro', palabraIncompleta: 'c_ntaro', vocalCorrecta: 'á', vocalIncorrecta: 'a', regla: 'Las palabras esdrújulas siempre llevan tilde.' },
  { palabraCompleta: 'nariz', palabraIncompleta: 'nar_z', vocalCorrecta: 'i', vocalIncorrecta: 'í', regla: 'Las palabras agudas que no terminan en vocal, -n o -s no llevan tilde.' },
  { palabraCompleta: 'álbum', palabraIncompleta: '_lbum', vocalCorrecta: 'á', vocalIncorrecta: 'a', regla: 'Las palabras llanas llevan tilde si NO terminan en vocal, -n o -s.' },
  { palabraCompleta: 'libélula', palabraIncompleta: 'lib_lula', vocalCorrecta: 'é', vocalIncorrecta: 'e', regla: 'Las palabras esdrújulas siempre llevan tilde.' },
  { palabraCompleta: 'interés', palabraIncompleta: 'inter_s', vocalCorrecta: 'é', vocalIncorrecta: 'e', regla: 'Las palabras agudas llevan tilde si terminan en vocal, -n o -s.' },
  { palabraCompleta: 'zapato', palabraIncompleta: 'zap_to', vocalCorrecta: 'a', vocalIncorrecta: 'á', regla: 'Las palabras llanas que terminan en vocal, -n o -s no llevan tilde.' },
  { palabraCompleta: 'vértigo', palabraIncompleta: 'v_rtigo', vocalCorrecta: 'é', vocalIncorrecta: 'e', regla: 'Las palabras esdrújulas siempre llevan tilde.' },
  { palabraCompleta: 'dolor', palabraIncompleta: 'dol_r', vocalCorrecta: 'o', vocalIncorrecta: 'ó', regla: 'Las palabras agudas que no terminan en vocal, -n o -s no llevan tilde.' },
  { palabraCompleta: 'célebre', palabraIncompleta: 'c_lebre', vocalCorrecta: 'é', vocalIncorrecta: 'e', regla: 'Las palabras esdrújulas siempre llevan tilde.' },
  { palabraCompleta: 'canción', palabraIncompleta: 'canci_n', vocalCorrecta: 'ó', vocalIncorrecta: 'o', regla: 'Las palabras agudas llevan tilde si terminan en vocal, -n o -s.' },
  { palabraCompleta: 'mástil', palabraIncompleta: 'm_stil', vocalCorrecta: 'á', vocalIncorrecta: 'a', regla: 'Las palabras llanas llevan tilde si NO terminan en vocal, -n o -s.' },
  { palabraCompleta: 'lámina', palabraIncompleta: 'l_mina', vocalCorrecta: 'á', vocalIncorrecta: 'a', regla: 'Las palabras esdrújulas siempre llevan tilde.' },
  { palabraCompleta: 'ordenador', palabraIncompleta: 'ordenad_r', vocalCorrecta: 'o', vocalIncorrecta: 'ó', regla: 'Las palabras agudas que no terminan en vocal, -n o -s no llevan tilde.' },
  { palabraCompleta: 'clímax', palabraIncompleta: 'cl_max', vocalCorrecta: 'í', vocalIncorrecta: 'i', regla: 'Las palabras llanas llevan tilde si NO terminan en vocal, -n o -s.' },
  { palabraCompleta: 'rídiculo', palabraIncompleta: 'r_diculo', vocalCorrecta: 'í', vocalIncorrecta: 'i', regla: 'Las palabras esdrújulas siempre llevan tilde.' },
  { palabraCompleta: 'avión', palabraIncompleta: 'avi_n', vocalCorrecta: 'ó', vocalIncorrecta: 'o', regla: 'Las palabras agudas llevan tilde si terminan en vocal, -n o -s.' },
  { palabraCompleta: 'resumen', palabraIncompleta: 'res_men', vocalCorrecta: 'u', vocalIncorrecta: 'ú', regla: 'Las palabras llanas que terminan en vocal, -n o -s no llevan tilde.' },
  { palabraCompleta: 'dámelo', palabraIncompleta: 'd_melo', vocalCorrecta: 'á', vocalIncorrecta: 'a', regla: 'Las palabras esdrújulas siempre llevan tilde.' },
  { palabraCompleta: 'ratón', palabraIncompleta: 'rat_n', vocalCorrecta: 'ó', vocalIncorrecta: 'o', regla: 'Las palabras agudas llevan tilde si terminan en vocal, -n o -s.' },
  { palabraCompleta: 'tórax', palabraIncompleta: 't_rax', vocalCorrecta: 'ó', vocalIncorrecta: 'o', regla: 'Las palabras llanas llevan tilde si NO terminan en vocal, -n o -s.' },
  { palabraCompleta: 'cómpralo', palabraIncompleta: 'c_mpralo', vocalCorrecta: 'ó', vocalIncorrecta: 'o', regla: 'Las palabras esdrújulas siempre llevan tilde.' }
];
